apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ma3fe3sx3-go
  janus-idp.io/tekton: ma3fe3sx3-go
  backstage.io/kubernetes-id: ma3fe3sx3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ma3fe3sx3-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
